# Site settings
title: Park Jude
email: park.jude.96@gmail.com
description: Park Jude Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://parkjude.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

google-analytics:
  id: "UA-92806731-1"

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
