# Site settings
title: Dainel Geek
email: topbladep@gmail.com
description: Dainel Geek's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dainelpark.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
